[package]
name = "rs-project-startup"
description = "A framework for quickly starting a Rust project"
version = "0.1.0"
edition = "2024"
authors = ["zunkk12345@gmail.com"]
homepage = "https://github.com/zunkk/rs-project-startup"
license = "Apache-2.0"
publish = false
repository = "https://github.com/zunkk/rs-project-startup"
build = "./build.rs"

[profile.release]
opt-level = 3
debug = 0
incremental = false
lto = "thin"
codegen-units = 16
panic = "unwind"
strip = "debuginfo"

[profile.performance]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "none"

[workspace]
members = ["crates/sidecar"]

[workspace.package]
edition = "2024"
authors = ["zunkk12345@gmail.com"]
homepage = "https://github.com/zunkk/rs-project-startup"
license = "Apache-2.0"
publish = false
repository = "https://github.com/zunkk/rs-project-startup"


[build-dependencies]
vergen-gitcl = { version = "10.0.0-beta.7", default-features = false, features = ["build", "cargo", "rustc", "si"] }

[dependencies]
# Internal crate dependencies.
sidecar = { path = "crates/sidecar" }

# External crate dependencies.
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
toml = { workspace = true }
axum = { workspace = true }
axum-client-ip = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
thiserror = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
humantime-serde = { workspace = true }
sea-orm = { workspace = true }
uuid = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
url = { workspace = true }
strip-ansi-escapes = { workspace = true }
color-eyre = { workspace = true }

[dev-dependencies]
regex = { workspace = true }
tempfile = { workspace = true }
serial_test = { workspace = true }

# Global workspace dependencies.
[workspace.dependencies]
eyre = { version = "0.6.12", default-features = false }
thiserror = { version = "2.0.18", default-features = false }
tokio = { version = "1.52.1", default-features = false, features = ["rt-multi-thread", "signal", "time", "macros", "fs"] }
tokio-util = { version = "0.7.18", default-features = false, features = ["rt"] }
serde = { version = "1.0.228", default-features = false }
serde_json = { version = "1.0.149", default-features = false }
humantime-serde = { version = "1.1.1", default-features = false }
dotenv = { version = "0.15.0", default-features = false }
async-trait = { version = "0.1.89", default-features = false }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.23", default-features = false }
tracing-appender = { version = "0.2.5", default-features = false }
chrono = { version = "0.4.44", default-features = false, features = ["clock"] }
clap = { version = "4.6.1", default-features = false, features = ["std", "derive"] }
once_cell = { version = "1.21.4", default-features = false }
tracing-panic = { version = "0.1.2", default-features = false }
config = { version = "0.15.22", default-features = false, features = ["toml", "convert-case"] }
toml = { version = "1.1.2", default-features = false, features = ["display"] }
color-eyre = { version = "0.6.5", default-features = false }
axum = { version = "0.8.9", default-features = false, features = ["http1", "original-uri", "query", "tokio"] }
url = { version = "2.5.8", default-features = false }
regex = { version = "1.12.3", default-features = false, features = ["unicode-perl"] }
axum-client-ip = { version = "1.3.1", default-features = false, features = ["forwarded-header"] }
utoipa = { version = "5.4.0", default-features = false }
utoipa-swagger-ui = { version = "9.0.2", default-features = false, features = ["axum", "vendored"] }
jsonwebtoken = { version = "10.3.0", default-features = false }
sea-orm = { version = "2.0.0-rc.38", default-features = false, features = ["macros", "with-chrono", "with-uuid", "sqlx-postgres", "runtime-tokio-rustls"] }
uuid = { version = "1.23.1", default-features = false, features = ["v4"] }
argon2 = { version = "0.6.0-rc.8", default-features = false, features = ["alloc", "getrandom"] }
rand = { version = "0.10.1", default-features = false, features = ["thread_rng"] }
reqwest = { version = "0.13.2", default-features = false, features = ["rustls"] }
reqwest-middleware = { version = "0.5.1", default-features = false, features = ["json", "query"] }
strip-ansi-escapes = { version = "0.2.1", default-features = false }
tempfile = { version = "3.27.0", default-features = false }
serial_test = { version = "3.4.0", default-features = false }
