/*
 * rs-project-startup
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use super::super::models;

/// LoginReq : 用户登录请求参数
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginReq {
    /// 外部账号唯一标识
    #[serde(rename = "auth_id")]
    pub auth_id: String,
    /// 登录凭证
    #[serde(rename = "auth_token")]
    pub auth_token: String,
    /// 登录方式 username：auth_id为用户名，auth_token为密码
    #[serde(rename = "auth_type")]
    pub auth_type: models::AuthType,
}

impl LoginReq {
    /// 用户登录请求参数
    pub fn new(auth_id: String, auth_token: String, auth_type: models::AuthType) -> LoginReq {
        LoginReq {
            auth_id,
            auth_token,
            auth_type,
        }
    }
}
