/*
 * rs-project-startup
 *
 * A framework for quickly starting a Rust project
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// LoginRes : User login response body
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginRes {
    /// Token expiration time (Unix timestamp, seconds)
    #[serde(rename = "expired_time")]
    pub expired_time: i64,
    /// Issued JWT token
    #[serde(rename = "jwt_token")]
    pub jwt_token: String,
    /// Unique identifier of the logged-in user
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl LoginRes {
    /// User login response body
    pub fn new(expired_time: i64, jwt_token: String, user_id: String) -> LoginRes {
        LoginRes {
            expired_time,
            jwt_token,
            user_id,
        }
    }
}
