/*
 * rs-project-startup
 *
 * A framework for quickly starting a Rust project
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use super::super::models;

/// LoginReq : User login request parameters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginReq {
    /// External account unique identifier
    #[serde(rename = "auth_id")]
    pub auth_id: String,
    /// Authentication credentials
    #[serde(rename = "auth_token")]
    pub auth_token: String,
    /// Authentication method username: auth_id is username, auth_token is password
    #[serde(rename = "auth_type")]
    pub auth_type: models::AuthType,
}

impl LoginReq {
    /// User login request parameters
    pub fn new(auth_id: String, auth_token: String, auth_type: models::AuthType) -> LoginReq {
        LoginReq {
            auth_id,
            auth_token,
            auth_type,
        }
    }
}
