/*
 * rs-project-startup
 *
 * A framework for quickly starting a Rust project
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RegisterRes : User registration response body
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterRes {
    /// Unique identifier of the newly created user
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl RegisterRes {
    /// User registration response body
    pub fn new(user_id: String) -> RegisterRes {
        RegisterRes { user_id }
    }
}
