/*
 * rs-project-startup
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use super::super::models;

/// RegisterReq : 用户注册请求体
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterReq {
    /// 外部账号唯一标识
    #[serde(rename = "auth_id")]
    pub auth_id: String,
    /// 登录凭证
    #[serde(rename = "auth_token")]
    pub auth_token: String,
    /// 登录方式 username：auth_id为用户名，auth_token为密码
    #[serde(rename = "auth_type")]
    pub auth_type: models::AuthType,
    /// 用户描述信息，默认为空
    #[serde(rename = "desc", skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
    /// 用户昵称，未填写时自动生成
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// 目标角色
    #[serde(rename = "role")]
    pub role: models::Role,
}

impl RegisterReq {
    /// 用户注册请求体
    pub fn new(
        auth_id: String,
        auth_token: String,
        auth_type: models::AuthType,
        role: models::Role,
    ) -> RegisterReq {
        RegisterReq {
            auth_id,
            auth_token,
            auth_type,
            desc: None,
            name: None,
            role,
        }
    }
}
