/*
 * rs-project-startup
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ResponseRefreshTokenResData : 刷新JWT Token响应体
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseRefreshTokenResData {
    /// 凭证过期时间（Unix 时间戳，秒）
    #[serde(rename = "expired_time")]
    pub expired_time: i64,
    /// 颁发的 JWT 凭证
    #[serde(rename = "jwt_token")]
    pub jwt_token: String,
    /// 登录用户唯一标识
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl ResponseRefreshTokenResData {
    /// 刷新JWT Token响应体
    pub fn new(
        expired_time: i64,
        jwt_token: String,
        user_id: String,
    ) -> ResponseRefreshTokenResData {
        ResponseRefreshTokenResData {
            expired_time,
            jwt_token,
            user_id,
        }
    }
}
