/*
 * rs-project-startup
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ResponseRegisterResData : 用户注册响应体
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseRegisterResData {
    /// 新创建用户的唯一标识
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl ResponseRegisterResData {
    /// 用户注册响应体
    pub fn new(user_id: String) -> ResponseRegisterResData {
        ResponseRegisterResData { user_id }
    }
}
