/*
 * rs-project-startup
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ResponseString : 对外暴露的统一错误响应
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseString {
    #[serde(rename = "code")]
    pub code: i64,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    #[serde(rename = "msg")]
    pub msg: String,
}

impl ResponseString {
    /// 对外暴露的统一错误响应
    pub fn new(code: i64, msg: String) -> ResponseString {
        ResponseString {
            code,
            data: None,
            msg,
        }
    }
}
