/*
 * rs-project-startup
 *
 * A framework for quickly starting a Rust project
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "Admin")]
    Admin,
    #[serde(rename = "Manager")]
    Manager,
    #[serde(rename = "User")]
    User,
}

impl std::fmt::Display for Role {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Admin => write!(f, "Admin"),
            Self::Manager => write!(f, "Manager"),
            Self::User => write!(f, "User"),
        }
    }
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}
